name: Build Flutter APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'

      - name: Find and Build APK
        run: |
          echo "Searching for main.dart..."
          MAIN_PATH=$(find . -name "main.dart" | head -n 1)
          if [ -z "$MAIN_PATH" ]; then
            echo "Error: main.dart not found anywhere!"
            exit 1
          fi
          echo "Found main.dart at: $MAIN_PATH"
          
          # استخراج مجلد المشروع الرئيسي بناءً على موقع ملف main.dart
          PROJECT_DIR=$(dirname $(dirname "$MAIN_PATH"))
          echo "Project directory: $PROJECT_DIR"
          
          cd "$PROJECT_DIR"
          flutter pub get
          flutter build apk --release -t lib/main.dart

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sym-app-apk
          path: '**/build/app/outputs/flutter-apk/app-release.apk'
